Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Models/PeopleTbl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domican_Stephen_S00209029_Web_Application_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PeopleTbl
    {
        [Display(Name = "ID")]
        public int PersonID { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Profession { get; set; }
        public string Bio { get; set; }
        public byte[] Image { get; set; }
    }
}

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Controllers/PeopleTblsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Domican_Stephen_S00209029_Web_Application_Project.Models;

namespace Domican_Stephen_S00209029_Web_Application_Project.Controllers
{
    public class PeopleTblsController : Controller
    {
        private PeopleAndPlacesDBEntities db = new PeopleAndPlacesDBEntities();

        // GET: PeopleTbls/Names
        public ActionResult Names()
        {
           

            //API's info page says it needs a string, so we create one here.
            string theVaueToDisplay;
           
           //Create a HTTPClient object to connect to the API. Class lets you send/receive HTTP requests/responses.
           HttpClient client = new HttpClient();
           client.BaseAddress = new Uri("http://localhost:56942/api/");
            
          var httpResponseMessage = client.GetAsync("GetNames");

          httpResponseMessage.Wait();

          var responseMessageFromApi = httpResponseMessage.Result;

          if (responseMessageFromApi.IsSuccessStatusCode)
          {
              var taskObjectRepresentingString = responseMessageFromApi.Content.ReadAsAsync<string>();
              taskObjectRepresentingString.Wait();

              theVaueToDisplay = taskObjectRepresentingString.Result;

              //viewbag lets you share info from controller in the view
              ViewBag.InfoFromNameAPI = theVaueToDisplay;
            }
            else
            {
                ViewBag.InfoFromNameAPI = "Error";
                ModelState.AddModelError(string.Empty, "No API available");
            }

            return View();
        }

        // GET: PeopleTbls
        public ActionResult Index()
        {
            return View(db.PeopleTbl.ToList());
        }

        // GET: PeopleTbls/Details/5
        [HandleError]
        public ActionResult Details(int? id)
        {

            if (id <= 0)
            {
                //New code that throws an exception of our choosing.
                throw new Exception("Id exception error");
            }


            if (id == null)
            {
                throw new HttpException(400, "400 error");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            PeopleTbl peopleTbl = db.PeopleTbl.Find(id);
            
            if (peopleTbl == null)
            {
                throw new HttpException(404, "404 error");
                //return HttpNotFound();
            }
            return View(peopleTbl);
        }

        // GET: PeopleTbls/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PeopleTbls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,FirstName,LastName,Profession,Bio")] PeopleTbl peopleTbl, HttpPostedFileBase PersonImageFileInput)
        {
            if (ModelState.IsValid)
            {
                if (PersonImageFileInput != null)
                {
                    peopleTbl.Image = new byte[PersonImageFileInput.ContentLength];
                    PersonImageFileInput.InputStream.Read(peopleTbl.Image, 0, PersonImageFileInput.ContentLength);
                }

                db.PeopleTbl.Add(peopleTbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(peopleTbl);
        }

        // GET: PeopleTbls/Edit/5
        public ActionResult Edit(int? id)
        {


            if (id == null)
            {
                throw new HttpException(400, "400 error");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (id <= 0)
            {
                throw new HttpException(400, "400 error");
            }

            PeopleTbl peopleTbl = db.PeopleTbl.Find(id);
            if (peopleTbl == null)
            {
                throw new HttpException(404, "404 error");
                //return HttpNotFound();
            }


            return View(peopleTbl);
        }

        // POST: PeopleTbls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,FirstName,LastName,Profession,Bio")] PeopleTbl peopleTbl, HttpPostedFileBase PersonImageFileInput)
        {
            if (ModelState.IsValid)
            {
                if (PersonImageFileInput != null)
                {
                    peopleTbl.Image = new byte[PersonImageFileInput.ContentLength];
                    PersonImageFileInput.InputStream.Read(peopleTbl.Image, 0, PersonImageFileInput.ContentLength);
                }

                db.Entry(peopleTbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(peopleTbl);
        }

        // GET: PeopleTbls/Delete/5
        public ActionResult Delete(int? id)
        {
            
            if (id == null)
            {
                throw new HttpException(400, "400 error");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            if (id <= 0)
            {
                throw new HttpException(400, "400 error");
            }

            PeopleTbl peopleTbl = db.PeopleTbl.Find(id);
            if (peopleTbl == null)
            {
                throw new HttpException(404, "404 error");
                //return HttpNotFound();
            }
            return View(peopleTbl);
        }

        // POST: PeopleTbls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PeopleTbl peopleTbl = db.PeopleTbl.Find(id);
            db.PeopleTbl.Remove(peopleTbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Create.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new character</h2>


@using (Html.BeginForm("Create", "PeopleTbls", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add new character to database</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="PersonImageFileInput" name="PersonImageFileInput" />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
*@

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Delete.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete character</h2>

<h3>Are you sure you want to delete character @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)?</h3>
<div>
    <h4>Character details:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(Model.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />
            }
            else
            {
                <span>No Image Found</span>
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Details.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(Model.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />
            }
            else
            {
                <span>No Image Found</span>
            }

            @*@Html.DisplayFor(model => model.Image)*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PersonID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Edit.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><h2>Edit details for @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h2></h2>


@using (Html.BeginForm("Edit", "PeopleTbls", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Information stored in database:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="PersonImageFileInput" name="PersonImageFileInput" />

                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
*@

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Index.cshtml
@model IEnumerable<Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl>

@{
    ViewBag.Title = "People List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>People List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profession)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bio)
        </td>
        <td>
            @if (item.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(item.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />

            }
            else
            {
                <span>No Image Found</span>
            }



            @*@Html.DisplayFor(modelItem => item.Image)*@
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PersonID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PersonID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PersonID })
        </td>
    </tr>
}

</table>

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PeopleTbls/Names.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PeopleTbl
@*Website connects to an API which provides a random name that is generated from a randomly selected first name and random surname taken from the API's database.*@
<h2>Generate random character names</h2>

<p>Struggling to come up with a name for a character in the novel you are writing?</p>
<p>Use the name generator below to come up with some ideas.</p>
<p></p>
<br />
<p style="font-weight:bold; font-size : large">Random name generated is @ViewBag.InfoFromNameAPI</p>
<p></p>
<br />
<button type="button" onClick="window.location.reload();" class="btn btn-primary">Generate Another Random Name</button>
<p></p>