Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Models/PlacesTbl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domican_Stephen_S00209029_Web_Application_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PlacesTbl
    {
        [Display(Name = "ID")]
        public int PlacesID { get; set; }
        [Display(Name = "Name")]
        public string PlaceName { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        [Display(Name = "Location Type")]
        public string PlaceType { get; set; }
        public byte[] Image { get; set; }
    }
}

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Controllers/PlacesTblsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Domican_Stephen_S00209029_Web_Application_Project.Models;

namespace Domican_Stephen_S00209029_Web_Application_Project.Controllers
{
    public class PlacesTblsController : Controller
    {
        private PeopleAndPlacesDBEntities db = new PeopleAndPlacesDBEntities();

        // GET: PlacesTbls
        public ActionResult Index()
        {
            return View(db.PlacesTbl.ToList());
        }

        // GET: PlacesTbls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "400 error");
            }

            if (id <= 0)
            {
                throw new HttpException(400, "400 error");
            }

            PlacesTbl placesTbl = db.PlacesTbl.Find(id);

            if (placesTbl == null)
            {
                throw new HttpException(404, "404 error");
            }

            //Code that requests info from our API is here

            //API's info page says it needs a string, so we create one here.
            string theVaueToDisplay;

            //Create a HTTPClient object to connect to the API. Class lets you send/receive HTTP requests/responses.
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:56942/api/");

            var httpResponseMessage = client.GetAsync("GetPlaceInfo/" + placesTbl.Location);

            //Needs to wait for responseMessage thread to work
            httpResponseMessage.Wait();

            var responseMessageFromApi = httpResponseMessage.Result;

            if (responseMessageFromApi.IsSuccessStatusCode)
            {
                var taskObjectRepresentingString = responseMessageFromApi.Content.ReadAsAsync<string>();
                taskObjectRepresentingString.Wait();

                theVaueToDisplay = taskObjectRepresentingString.Result;

                //viewbag lets you share info from controller in the view
                ViewBag.InfoFromAPI = theVaueToDisplay;
            }
            else
            {
                ViewBag.InfoFromAPI = "Error";
                ModelState.AddModelError(string.Empty, "No API available");
            }

            return View(placesTbl);
        }

        // GET: PlacesTbls/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlacesTbls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlacesID,PlaceName,Location,Notes,PlaceType")] PlacesTbl placesTbl, HttpPostedFileBase PlaceImageFileInput)
        {
            if (ModelState.IsValid)
            {

                if (PlaceImageFileInput != null)
                {
                    placesTbl.Image = new byte[PlaceImageFileInput.ContentLength];
                    PlaceImageFileInput.InputStream.Read(placesTbl.Image, 0, PlaceImageFileInput.ContentLength);
                }


                db.PlacesTbl.Add(placesTbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(placesTbl);
        }

        // GET: PlacesTbls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw new HttpException(404, "Place not found");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (id <= 0)
            {
                throw new HttpException(400, "400 error");
            }

            PlacesTbl placesTbl = db.PlacesTbl.Find(id);
            if (placesTbl == null)
            {
                throw new HttpException(400, "400 error");
                //return HttpNotFound();
            }
            return View(placesTbl);
        }

        // POST: PlacesTbls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlacesID,PlaceName,Location,Notes,PlaceType")] PlacesTbl placesTbl, HttpPostedFileBase PlaceImageFileInput)
        {
            if (ModelState.IsValid)
            {
                if (PlaceImageFileInput != null)
                {
                    placesTbl.Image = new byte[PlaceImageFileInput.ContentLength];
                    PlaceImageFileInput.InputStream.Read(placesTbl.Image, 0, PlaceImageFileInput.ContentLength);
                }

                db.Entry(placesTbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(placesTbl);
        }

        // GET: PlacesTbls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                throw new HttpException(404, "404 error");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            if (id <= 0)
            {
                throw new HttpException(400, "400 error");
            }

            PlacesTbl placesTbl = db.PlacesTbl.Find(id);
            if (placesTbl == null)
            {
                throw new HttpException(404, "404 error");
            }
            return View(placesTbl);
        }

        // POST: PlacesTbls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PlacesTbl placesTbl = db.PlacesTbl.Find(id);
            db.PlacesTbl.Remove(placesTbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PlacesTbls/Create.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PlacesTbl

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new location</h2>


@using (Html.BeginForm("Create", "PlacesTbls", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add new location to database</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="PlaceImageFileInput" name="PlaceImageFileInput" />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
*@

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PlacesTbls/Delete.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PlacesTbl

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlacesTbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(Model.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />
            }
            else
            {
                <span>No Image Found</span>
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PlacesTbls/Details.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PlacesTbl

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete location</h2>

<div>
    <h4>Are you sure you want to delete  @Html.DisplayNameFor(model => model.Location)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(Model.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />
            }
            else
            {
                <span>No Image Found</span>
            }

            @*
            @Html.DisplayFor(model => model.Image)
            *@
        </dd>
        <dt>
            <label>More information</label>
        </dt>
        <dd>
            @ViewBag.InfoFromApi
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PlacesID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PlacesTbls/Edit.cshtml
@model Domican_Stephen_S00209029_Web_Application_Project.Models.PlacesTbl

@{
    ViewBag.Title = "Edit Place";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit details for @Html.DisplayFor(model => model.PlaceName)</h2>


@using (Html.BeginForm(Html.BeginForm("Edit", "PlacesTbls", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Information stored in database:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PlacesID)

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="PlaceImageFileInput" name="PlaceImageFileInput" />

                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
*@

Domican_Stephen_S00209029_Web_Application_Project/Domican_Stephen_S00209029_Web_Application_Project/Views/PlacesTbls/Index.cshtml
@model IEnumerable<Domican_Stephen_S00209029_Web_Application_Project.Models.PlacesTbl>

@{
    ViewBag.Title = "Places List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Places List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlaceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceType)
        </td>
        <td>
            @if (item.Image != null)
            {
                var imageAsBase64String = Convert.ToBase64String(item.Image);
                var imageAsGif = string.Format("data:image/gif; base64, {0}", imageAsBase64String);
                <img src="@imageAsGif" class="img-circle" style="max-height:100px; max-width:100px" />

            }
            else
            {
                <span>No Image Found</span>
            }

            @*
            @Html.DisplayFor(modelItem => item.Image)
            *@
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlacesID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlacesID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlacesID })
        </td>
    </tr>
}

</table>